### ISSUE TITLE
Add pagination to REST API list views

### ISSUE THREAD

**Issue by holtgrewe** [bihealth/sodar-core#1313]
### Problem

There is a number of endpoints that return lists of objects. Some consider it a good idea to paginate all output and never get a list of arbitrary number results. In particular, AWS Smithy assumes all REST endpoint output to be a objects rather than lists.

### Solution

- Review all endpoints and identify those that return plain lists as endpoints.
- Implement pagination using the [appropriate DRF feature: pagination](https://www.django-rest-framework.org/api-guide/pagination/)

### Alternative Solutions

- Adjust the endpoints to return an object with `items` key (or similar) that returns the list of objects.

### Additional Context

- https://stackoverflow.com/questions/77387109/representing-list-at-root-of-output-in-aws-smithy

**Comment by mikkonie** [comment]
This can be considered. Having pagination applied as default seems a bit weird, since when I query for data in a REST API, handling paginated results isn't really in the top of my priorities. As an optional choice, why not.

Also deviating from the standard output of DRF and serializers with an additional object structure seems like a questionable choice. I'm sure Smithy is a nice tool, but should it really be the one and only standard to follow?

**Comment by holtgrewe** [comment]
DRF has [builtin support for pagination](https://www.django-rest-framework.org/api-guide/pagination/). This is done on the level of views, though, not serializers.

**Comment by mikkonie** [comment]
Done. I added this in a non-breaking way, because I know most current clients don't care about the (now former) versioning. We can remove the support for non-paginated results in v2.0 of the APIs if it's deemed appropriate.
